### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by labay11** [urisawsing/Covid_GeneticAlg#2]
Es podria fer algo com implementar immigració al GA.

Osigui ara el que fas es la seleccio amb el roulette wheel, crossover i mutation. La migració afegiria un % de individus completament nous a la poblacio despres de la mutacio, per afegir mes variabilitat.

**Comment by urisawsing** [comment]
ou, realment estaria guai aixo, per l'informe molaria posar  la versio
sense aixo i despres posarho a veure si troba millors coses o que

**Comment by labay11** [comment]
Inclus es podria fer un GA que optimitzes els % de selection, cross, immigration per a que convergis avanç! :rocket: un MetaGA
